name: Improve the docs.insomnia.rest site
description: Make a suggestion or report a problem about the technical implementation of docs.insomnia.rest.
labels:
  - content
body:
  - type: markdown
    id: intro-to-contribution
    attributes:
      value: |
        Thank you for your interest in opening up a site improvements issue for the Insomnia Docs!

        * For Insomnia support, head over to [our Support page](https://insomnia.rest/support). 
        * Before you file an issue read the [Contributing guide](../CONTRIBUTING.md) and [Community Expectations](https://docs.konghq.com/contributing/community-expectations/).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/Kong/insomnia-docs/issues).
        * Note that we don't store [Plugin Hub docs](https://insomnia.rest/plugins) here - those are pulled in using a query to NPM!

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: what-affected
    attributes:
      label: What article on docs.insomnia.rest is affected?
      description: Please link to the article you'd like to see updated.
    validations:
      required: true

  - type: textarea
    id: what-needs-updating
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct and Community Expectations
      description: |
          By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md) and [Community Expectations](https://docs.konghq.com/contributing/community-expectations/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I agree to abide by the Community Expectations
          required: true
