on:
  schedule:
  - cron: '0 0 * * *'

  workflow_dispatch:

name: Update Algolia indice every day
jobs:
  updateAlgoliaIndexFullDocs:
    name: Index Insomnia Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run docsearch for Insomnia Docs
      uses: darrenjennings/algolia-docsearch-action@75b0f6d28d82eff3dd76f57a96a99490df11a250 # master
      with:
        algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
        algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        file: search-config/insomnia_docs.json
